network:
  version: 2
  renderer: networkd
  ethernets:
    ens18: {dhcp4: no}
    ens19: {dhcp4: no}
    ens20: {dhcp4: no}
    ens21: {dhcp4: no}
    ens22: {dhcp4: no}
  bridges:
    br0:
      interfaces: [ens18, ens19, ens20, ens21, ens22]
      addresses:
        - 10.0.10.1/24
        - 10.0.20.1/24
        - 10.0.30.1/24
        - 10.0.40.1/24
        - 10.0.255.0/24